version: "3"

services:
  app:
    volumes: &appvolumes
      - ${GITPOD_REPO_ROOT}/nginx.conf.sample:/var/www/html/nginx.conf:cached
      - ${GITPOD_REPO_ROOT}:/var/www/html:cached

  phpfpm:
    volumes: *appvolumes
